In [1]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})

In [3]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})


In [4]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [5]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [6]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [7]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [8]:
 df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})

In [9]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],'data2': range(3)})

In [10]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [11]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [12]:
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],'data2': range(5)})

In [13]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [14]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [15]:
pd.merge(df1, df2, on='key', how='left')


key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [16]:
pd.merge(df1, df2, how='inner')

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [17]:
 left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],'key2': ['one', 'two', 'one'],'lval': [1, 2, 3]})


In [18]:
 right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],'key2': ['one', 'one', 'one', 'two'],'rval': [4, 5, 6, 7]})


In [19]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [20]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [21]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],'value': range(6)})

In [22]:
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [23]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [24]:
right1

group_val
a        3.5
b        7.0

In [25]:
 pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [26]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [27]:
 lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],'key2': [2000, 2001, 2002, 2001, 2002],'data': np.arange(5.)})


In [28]:
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],[2001, 2000, 2000, 2000, 2001, 2002]],columns=['event1', 'event2'])


In [29]:
lefth

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [30]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [31]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

In [32]:
 pd.merge(lefth, righth, left_on=['key1', 'key2'],right_index=True, how='outer')


key1  key2  data  event1  event2
0    Ohio  2000   0.0     4.0     5.0
0    Ohio  2000   0.0     6.0     7.0
1    Ohio  2001   1.0     8.0     9.0
2    Ohio  2002   2.0    10.0    11.0
3  Nevada  2001   3.0     0.0     1.0
4  Nevada  2002   4.0     NaN     NaN
4  Nevada  2000   NaN     2.0     3.0

In [33]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 'c', 'e'],columns=['Ohio', 'Nevada'])

In [34]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])

In [35]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [36]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [37]:
left1.join(right1, on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [38]:
 another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],index=['a', 'c', 'e', 'f'], columns=['New York', 'Oregon'])

In [39]:
left2.join([right2, another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [40]:
left2.join([right2, another], how='outer')

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0
b   NaN     NaN       7.0      8.0       NaN     NaN
d   NaN     NaN      11.0     12.0       NaN     NaN
f   NaN     NaN       NaN      NaN      16.0    17.0

In [41]:
arr = np.arange(12).reshape((3, 4))

In [42]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [44]:
s1 = pd.Series([0, 1], index=['a', 'b'])

In [45]:
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])

In [46]:
s3 = pd.Series([5, 6], index=['f', 'g'])

In [47]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [48]:
pd.concat([s1, s2, s3], axis=1)


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [49]:
s4 = pd.concat([s1 * 5, s3])

In [50]:
pd.concat([s1, s4], axis=1) 

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [51]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  5

In [52]:
pd.concat([s1, s4], axis=1).reindex(['a', 'c', 'b', 'e'])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [53]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])

In [54]:
 result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [55]:
 result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [56]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [57]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],columns=['one', 'two'])


In [58]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],columns=['three', 'four'])


In [59]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [60]:
pd.concat({'level1': df1, 'level2': df2}, axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [61]:
 pd.concat([df1, df2], axis=1, keys=['level1', 'level2'],names=['upper', 'lower'])


upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [62]:
 df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])

In [63]:
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [64]:
df1

a         b         c         d
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221

In [65]:
df2

b         d         a
0  0.274992  0.228913  1.352917
1  0.886429 -2.001637 -0.371843

In [66]:
 pd.concat([df1, df2], ignore_index=True)

a         b         c         d
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  1.352917  0.274992       NaN  0.228913
4 -0.371843  0.886429       NaN -2.001637

In [67]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],index=['f', 'e', 'd', 'c', 'b', 'a'])


In [68]:
b = pd.Series(np.arange(len(a), dtype=np.float64),index=['f', 'e', 'd', 'c', 'b', 'a'])

In [69]:
b[-1] = np.nan

In [70]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [71]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [72]:
np.where(pd.isnull(a), b, a)


array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [73]:
 b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [74]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],'b': [np.nan, 2., np.nan, 6.],'c': range(2, 18, 4)})

In [75]:
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],'b': [np.nan, 3., 4., 6., 8.]})


In [76]:
df1.combine_first(df2)


a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [77]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),index=pd.Index(['Ohio', 'Colorado'], name='state'),
columns=pd.Index(['one', 'two', 'three'], name='number'))


In [78]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [79]:
result = data.stack()

In [80]:
result
    

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [81]:
result.unstack()
        
    

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [82]:
result.unstack(0) 

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [83]:
result.unstack('state')


state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [84]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])

In [85]:
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])


In [86]:
data2 = pd.concat([s1, s2], keys=['one', 'two'])


In [87]:
data2.unstack()


a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [88]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [89]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [90]:
 df= pd.DataFrame({'left': result, 'right': result + 5},columns=pd.Index(['left', 'right'], name='side'))


In [91]:
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [92]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [93]:
df.unstack('state').stack('side')


state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7

In [94]:
data = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4,'k2': [1, 1, 2, 3, 3, 4, 4]})

In [95]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [96]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [97]:
data.drop_duplicates()


k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [98]:
data['v1'] = range(7)


In [99]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [100]:
data.drop_duplicates(['k1', 'k2'])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [101]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})


In [102]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [103]:
meat_to_animal = {
 'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'
}

In [104]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [105]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [106]:
 data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [107]:
 data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [108]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [109]:
 data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [110]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [111]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [112]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [113]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])

In [114]:
data.index.map(str.upper)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [115]:
data.index = data.index.map(str.upper)

In [116]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [117]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [118]:
 data.rename(index={'OHIO': 'INDIANA'},columns={'three': 'peekaboo'})



one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [119]:
 _ = data.rename(index={'OHIO': 'INDIANA'}, inplace=True)


In [120]:
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

# Discretization and Binning

In [121]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]


In [122]:
bins = [18, 25, 35, 60, 100]


In [123]:
cats = pd.cut(ages, bins)


In [124]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [125]:
type(cats)

pandas.core.arrays.categorical.Categorical

In [126]:

cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [127]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [128]:
 pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [129]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [130]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [131]:
 data = np.random.rand(20)


In [132]:
pd.cut(data, 4, precision=2)

[(0.27, 0.51], (0.51, 0.75], (0.75, 0.99], (0.51, 0.75], (0.75, 0.99], ..., (0.51, 0.75], (0.75, 0.99], (0.27, 0.51], (0.75, 0.99], (0.024, 0.27]]
Length: 20
Categories (4, interval[float64, right]): [(0.024, 0.27] < (0.27, 0.51] < (0.51, 0.75] < (0.75, 0.99]]

In [133]:
data = np.random.randn(1000) # Normally distributed


In [134]:
 cats = pd.qcut(data, 4) # Cut into quartiles

In [135]:
cats

[(-2.9499999999999997, -0.691], (-2.9499999999999997, -0.691], (-2.9499999999999997, -0.691], (-2.9499999999999997, -0.691], (-2.9499999999999997, -0.691], ..., (-2.9499999999999997, -0.691], (0.62, 3.928], (0.62, 3.928], (-0.691, -0.0192], (-0.0192, 0.62]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9499999999999997, -0.691] < (-0.691, -0.0192] < (-0.0192, 0.62] < (0.62, 3.928]]

In [136]:
pd.value_counts(cats)

(-2.9499999999999997, -0.691]    250
(-0.691, -0.0192]                250
(-0.0192, 0.62]                  250
(0.62, 3.928]                    250
dtype: int64

In [137]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.212, -0.0192], (-1.212, -0.0192], (-2.9499999999999997, -1.212], (-2.9499999999999997, -1.212], (-1.212, -0.0192], ..., (-2.9499999999999997, -1.212], (-0.0192, 1.287], (1.287, 3.928], (-1.212, -0.0192], (-0.0192, 1.287]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9499999999999997, -1.212] < (-1.212, -0.0192] < (-0.0192, 1.287] < (1.287, 3.928]]

# Detecting and Filtering Outliers


In [138]:
np.random.seed(12345)

In [139]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [140]:
data.describe()


0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [141]:
col = data[3]


In [142]:
col[np.abs(col) > 3]


97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [143]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [144]:
data[np.abs(data) > 3] = np.sign(data) * 3


In [145]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

# Permutation and Random Sampling

In [146]:
df = pd.DataFrame(np.arange(5 * 4).reshape(5, 4))


In [147]:
sampler = np.random.permutation(5)


In [148]:
sampler

array([1, 0, 2, 3, 4])

In [149]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [150]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [151]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

In [152]:
bag = np.array([5, 7, -1, 6, 4])

In [153]:
sampler = np.random.randint(0, len(bag), size=10)

In [154]:
sampler

array([4, 4, 2, 2, 2, 0, 3, 0, 4, 1])

In [155]:
draws = bag.take(sampler)

In [156]:
draws

array([ 4,  4, -1, -1, -1,  5,  6,  5,  4,  7])

# Computing Indicator/Dummy Variables

In [157]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})

In [158]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [159]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [160]:
df_with_dummy = df[['data1']].join(dummies)


In [161]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [162]:
mnames = ['movie_id', 'title', 'genres']

In [163]:
movies = pd.read_table('movies.dat', engine='python',sep='::', header=None,
 .....: names=mnames)

In [164]:
movies[:10]


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [165]:
genre_iter = (set(x.split('|')) for x in movies.genres)


In [166]:
genres = sorted(set.union(*genre_iter))

In [167]:
dummies = pd.DataFrame(np.zeros((len(movies), len(genres))), columns=genres)

In [168]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [169]:
 values = np.random.rand(10)

In [170]:
values

array([0.756 , 0.9083, 0.9659, 0.1737, 0.8759, 0.7542, 0.1635, 0.2378,
       0.8556, 0.5874])

In [171]:
pd.get_dummies(pd.cut(values, bins))

(18, 25]  (25, 35]  (35, 60]  (60, 100]
0         0         0         0          0
1         0         0         0          0
2         0         0         0          0
3         0         0         0          0
4         0         0         0          0
5         0         0         0          0
6         0         0         0          0
7         0         0         0          0
8         0         0         0          0
9         0         0         0          0

# String Manipulation

In [172]:
val = 'a,b, guido'


In [173]:
val.split(',')


['a', 'b', ' guido']

In [174]:
 pieces = [x.strip() for x in val.split(',')]
pieces


['a', 'b', 'guido']

In [175]:
first, second, third = pieces


In [176]:
first + '::' + second + '::' + third

'a::b::guido'

In [177]:
'::'.join(pieces)

'a::b::guido'

In [178]:
'guido' in val

True

In [179]:
 val.index(',')

1

In [180]:
val.find(':')

-1

In [182]:
val.index(':')

ValueError: substring not found

In [183]:
val.count(',')

2

In [184]:
val.replace(',', '::') 

'a::b:: guido'

In [185]:
val.replace(',', '')

'ab guido'

# Regular expressions

In [186]:
import re


In [187]:
text = "foo bar\t baz \tqux"


In [188]:
re.split('\s+', text)


['foo', 'bar', 'baz', 'qux']

In [189]:
regex = re.compile('\s+')


In [190]:
regex.split(text)


['foo', 'bar', 'baz', 'qux']

In [191]:
regex.findall(text)


[' ', '\t ', ' \t']

In [192]:
regex.findall(text)


[' ', '\t ', ' \t']

In [193]:
regex.findall(text)

[' ', '\t ', ' \t']

In [194]:
m = regex.search(text)


In [195]:
m

<re.Match object; span=(3, 4), match=' '>

In [196]:
text[m.start():m.end()]

' '

In [197]:
print (regex.match(text))

None


In [198]:
print (regex.sub('REDACTED', text))


fooREDACTEDbarREDACTEDbazREDACTEDqux


In [199]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [200]:
regex = re.compile(pattern, flags=re.IGNORECASE)


In [201]:
m = regex.match('wesm@bright.net')

In [202]:
 m.groups()


('wesm', 'bright', 'net')

In [203]:
regex.findall(text)

[]

In [204]:
print (regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

foo bar	 baz 	qux


In [205]:
m = regex.match('wesm@bright.net')

In [206]:
m.groupdict()


{}

# Vectorized string functions in pandas

In [207]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com','Rob': 'rob@gmail.com', 'Wes': np.nan}

In [208]:
 data = pd.Series(data)

In [209]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [210]:
data.isnull()


Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [211]:
data.str.contains('gmail')


Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [212]:
pattern


'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [213]:
data.str.findall(pattern, flags=re.IGNORECASE)


Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [214]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [215]:
matches.get(1) 

True

In [216]:
matches[0]

True

In [217]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

# Example: USDA Food Database

In [218]:
import json


In [219]:
db = json.load(open('//usda_food/database.json'))

FileNotFoundError: [Errno 2] No such file or directory: '//usda_food/database.json'

In [220]:
len(db)

NameError: name 'db' is not defined